// Generated by CoffeeScript 1.8.0
// Contains the utility functions for loading files 
// from the disk onto the web page. 
(function() {
  var findConfig, getTextFile, playAudio;
 
  /**
   * Loads the configuration file containing styling
   * for the web page i.e. CSS files. 
   * @param loc the file path to the configuration file
   * @return the CSS data from the config file
   */
  findConfig = function(loc) {
    var cssData;
    cssData = null;
    $.ajax({
      url: loc,
      dataType: 'json',
      async: false,
      success: function(data) {
        return cssData = data;
      },
      error: function(jqXHR, st, err) {
        return console.log("Error loading:" + err);
      }
    });
    return cssData;
  };
	
  /**
   * Loads a text file from disk and returns the
   * data in raw format. 
   * @param loc the file path to load from
   * @return the text data from the file
   */
  getTextFile = function(loc) {
    var textData;
    textData = null;
    $.ajax({
      url: loc,
      dataType: 'text',
      async: false,
      success: function(data) {
        return textData = data;
      },
      error: function(jqXHR, st, err) {
        return console.log("Error loading:" + err);
      }
    });
    return textData;
  };
  
  /**
   * Automatically plays the sound file in the 
   * web/audio folder with the given name.
   * @param name the name of the sound file 
   */
  playAudio = function(name) {
    var sound;
    sound = document.createElement("video");
    $(sound).attr({
      "src": "audio/" + name,
      "autoplay": "true"
    });
  };

  window.playAudio = playAudio;

  window.findConfig = findConfig;

  window.getTextFile = getTextFile;

}).call(this);
