// Generated by CoffeeScript 1.8.0
// Sets up Node.js for the browser 
(function() {
  var mfs;

  BrowserFS.install(window);

  mfs = new BrowserFS.FileSystem.MountableFileSystem();

  mfs.mount('/tmp', new BrowserFS.FileSystem.InMemory());

  mfs.mount('/sys', new BrowserFS.FileSystem.XmlHttpRequest('/listings.json', 'doppio-jvm'));

  BrowserFS.initialize(mfs);

  window.node = BrowserFS.node;

  node.fs.mkdirSync('/tmp');

  node.process.chdir('/tmp');

}).call(this);
