// Generated by CoffeeScript 1.8.0
(function() {
  window.gameSelector = (function() {
    var config, cont;

    cont = null;

    config = null;

    function gameSelector(div, dis) {
      var tmp;
      this.div = div;
      this.dis = dis;
      $("#acelne").remove();
      config = findConfig('scripts/config/gameSelection.json');
      tmp = makeDiv(null, config["tmpCSS"]);
      cont = $(tmp);
      $(tmp).attr("id", "gameSelection");
      this.div.append(tmp);
      return;
    }

    gameSelector.prototype.buildDiv = function(count, game, desc, player, canPlay, codeland) {
      var img, span, src;
      span = document.createElement("span");
      $(span).css(config["spanCSS"]);
      $(span).attr("id", "select" + game);
      $(span).attr("class", "select" + count);
      cont.append(span);
      $(span).click(function() {
        return codeland.startGame(game);
      });
      if ((player != null ? player.passed : void 0) === true) {
        $(span).append("<b><font color=\"white\">" + count + ": " + desc.title + "</font></b> ");
        src = 'img/interface/star.png';
        img = $('<img>', {
          id: 'star',
          src: src,
          style: 'max-height:16px',
          alt: "Start Game"
        });
        return $(span).append(img.get(0));
      } else {
        return $(span).append("<font color=\"white\">" + count + ": " + desc.title + "</font>");
      }
    };

    gameSelector.prototype.buildAn = function(con, canPlay) {
      var images, problem, tmp2;
      tmp2 = makeImgElem(null, config["tmp2CSS"]);
      $(con).append(tmp2);
      images = config["images"];
      problem = function() {
        if ($(tmp2).attr("src") === images["womanFrontA"]) {
          return $(tmp2).attr("src", images["womanFrontB"]);
        } else {
          return $(tmp2).attr("src", images["womanFrontA"]);
        }
      };
      if (canPlay) {
        return setInterval(problem, 450);
      } else {
        return $(tmp2).attr("src", images["womanFrontA"]);
      }
    };

    gameSelector.prototype.buildScore = function(con, player) {
      var es, ns, tmp, tmp1, tmp2, tmp3, _i, _j, _ref, _ref1;
      tmp = makeDiv(null, config["tmpBuildScoreCSS"]);
      $(con).append(tmp);
      tmp1 = $('<p></p>');
      tmp2 = $('<p></p>');
      tmp3 = $('<p></p>');
      $(tmp).append(tmp1);
      $(tmp).append(tmp2);
      $(tmp).append(tmp3);
      if ((player != null ? player.passed : void 0) === true) {
        $(tmp1).text("Status:  Complete");
      } else {
        $(tmp1).text("Status:  Incomplete");
      }
      $(tmp2).text("Hi-Score: " + (player != null ? player.hiscore : 0));
      if (this.dis) {
        $(tmp3).text("Stars: " + (player != null ? player.stars : void 0));
      } else {
        for (ns = _i = 1, _ref = player != null ? player.stars : void 0; _i <= _ref; ns = _i += 1) {
          $(tmp).append("<img src='img/interface/star.png' width='20%' height='20%'></img>");
        }
        for (es = _j = _ref1 = player != null ? player.stars : void 0; _j < 3; es = _j += 1) {
          $(tmp).append("<img src='img/interface/stare.png' width='20%' height='20%'></img>");
        }
      }
    };

    gameSelector.prototype.buildInfo = function(con, desc) {
      var tmp, tmp1, tmp2;
      tmp = makeDiv(null, cssData["tmpBuildInfoCSS"]);
      $(con).append(tmp);
      tmp1 = $('<p></p>');
      tmp2 = $('<p></p>');
      $(tmp).append(tmp1);
      $(tmp).append(tmp2);
      $(tmp1).text("Name:  " + desc.name);
      return $(tmp2).text("Description:  " + desc.description);
    };

    gameSelector.prototype.canPlay = function(con, cp, codeland, game) {
      var over, ovr;
      if (cp) {
        return $(con).click(function() {
          return codeland.startGame(game);
        });
      } else {
        over = makeDiv(null, cssData["tmpOverCSS"]);
        ovr = $('<div></div>');
        return $(con).prepend(ovr);
      }
    };

    return gameSelector;

  })();

}).call(this);
