// Generated by CoffeeScript 1.8.0
(function() {
  window.appendBar = function(d) {
    var cont, cssData, edge, ref, sand, select, toggleDrawerInOut;
	
	/**
	* attaches the menu bar to the main screen
	* @param d the element to attach the menu bar to
	*/

    $("#acelne").remove();
    cssData = findConfig('scripts/config/menuBar.json');
    toggleDrawerInOut = function() {
      if ($(edge).attr("src") === "img/interface/barin.png") {
        $(cont).animate({
          "left": "0px"
        });
        $(cont).animate({
          "left": "-10px"
        });
        $(edge).attr({
          "src": "img/interface/barout.png"
        });
      } else {
        $(cont).animate({
          "left": "0px"
        });
        $(cont).animate({
          "left": "-150px"
        });
        $(edge).attr({
          "src": "img/interface/barin.png"
        });
      }
      return false;
    };
    cont = makeDiv(null, cssData["cont"]);
    edge = makeImgElem(cssData["edgeAttr"], cssData["edgeCSS"]);
    ref = makeImgElem(cssData["refAttr"], cssData["refCSS"]);
    select = makeImgElem(cssData["selectAttr"], cssData["selectCSS"]);
    sand = makeImgElem(cssData["sandAttr"], cssData["sandCSS"]);
    $(cont).append(ref);
    $(cont).append(select);
    $(cont).append(sand);
    $(cont).append(edge);
    $(ref).click(referencePage);
    $(select).click(codeland.showMap);
    $(sand).click(sandBoxPage);
    $(toggleDrawerInOut);
    return $(d).append(cont);
  };

}).call(this);
